export const aboutText = {
  id: {
    kicker: "// kenalan dulu",
    headingLine1: "TENTANG",
    headingLine2: "SAYA",
    bio1: "[ISI SENDIRI: cerita singkat tentang diri kamu — siapa kamu, apa yang kamu kerjakan, dan kenapa kamu suka bikin sesuatu. 2-3 kalimat.]",
    bio2: "[ISI SENDIRI: paragraf kedua, bisa cerita perjalanan belajar coding atau hal personal lain yang mau ditonjolkan. 2-3 kalimat.]",
    role1: "Fullstack Developer",
    role2: "SMK Telkom Malang — RPL",
    role3: "Berbasis di Malang, Indonesia",
    cardName: "Rahadyan Al Farisi",
    cardTitle: "Fullstack Developer",
    cardHandle: "rahadyan_al",
    cardStatus: "Available for work",
    cardContact: "Contact Me",
    cardHint: "arahkan kursor — kartu akan miring mengikuti gerakan",
  },
  en: {
    kicker: "// get to know me",
    headingLine1: "ABOUT",
    headingLine2: "ME",
    bio1: "[FILL IN: short story about yourself — who you are, what you do, and why you love building things. 2-3 sentences.]",
    bio2: "[FILL IN: second paragraph, you can tell your coding journey or other personal highlights. 2-3 sentences.]",
    role1: "Fullstack Developer",
    role2: "SMK Telkom Malang — Software Engineering",
    role3: "Based in Malang, Indonesia",
    cardName: "Rahadyan Al Farisi",
    cardTitle: "Fullstack Developer",
    cardHandle: "rahadyan_al",
    cardStatus: "Available for work",
    cardContact: "Contact Me",
    cardHint: "hover the card — it tilts following your cursor",
  },
};
