export const commonText = {
  id: {
    "nav.home": "Beranda",
    "nav.about": "Tentang",
    "nav.skill": "Skill",
    "nav.project": "Projek",
    "nav.certificate": "Sertifikat",
    "nav.sourceCode": "Source Code",
    "nav.contact": "Kontak",
    "footer.contactTitle": "HUBUNGI",
    "footer.infoTitle": "INFO",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.madeWith": "Made by R.A.F with love",
    "footer.copyright": "All rights reserved.",
    "sourceModal.title": "Pindah ke Github?",
    "sourceModal.desc": "Link ini membuka repo GitHub portofolio ini di tab baru. Kamu tetap di halaman ini.",
    "sourceModal.continue": "Lanjutkan",
    "sourceModal.back": "← Kembali",
    "notFound.title": "404",
    "notFound.desc": "Halaman yang kamu cari tidak ada. Mungkin sudah dihapus, atau kamu salah mengetik URL. Coba periksa kembali alamatnya, atau kembali ke halaman utama.",
    "notFound.back": "KEMBALI KE HOME →",
    "privacy.title": "PRIVACY POLICY",
    "privacy.updated": "Terakhir diperbarui: 15 September 2026 — placeholder, ganti dengan kebijakan asli jika diperlukan.",
    "privacy.intro":
      "Website portfolio ini menghormati privasi pengunjung. Halaman ini menjelaskan jenis informasi yang dikumpulkan dan bagaimana informasi tersebut digunakan. Ini adalah teks placeholder — silakan ganti dengan kebijakan privasi yang sesuai.",
    "privacy.s1.title": "1. Informasi yang Dikumpulkan",
    "privacy.s1.desc":
      "Form kontak di halaman Contact mengirimkan nama, email, dan pesan yang kamu isi ke layanan pihak ketiga (Web3Forms atau Formspree) untuk diteruskan ke email pemilik situs. Tidak ada data lain yang disimpan di server situs ini karena situs di-host sebagai static site di GitHub Pages.",
    "privacy.s2.title": "2. Penggunaan Informasi",
    "privacy.s2.desc":
      "Informasi yang dikirim lewat form hanya digunakan untuk membalas pesan dan tidak dibagikan ke pihak lain. Log anonim (seperti yang disediakan GitHub Pages) mungkin mencatat akses halaman untuk keperluan statistik tanpa mengidentifikasi individu.",
    "privacy.s3.title": "3. Cookies",
    "privacy.s3.desc":
      "Situs ini tidak menggunakan cookies pelacakan. Preferensi bahasa disimpan di localStorage browser (portfolio:language) dan tidak dikirim ke server.",
    "privacy.s4.title": "4. Tautan Eksternal",
    "privacy.s4.desc":
      "Tautan ke GitHub, LinkedIn, dan Instagram akan membuka situs pihak ketiga dengan kebijakan privasi masing-masing. Harap tinjau kebijakan mereka sebelum berinteraksi lebih lanjut.",
    "privacy.s5.title": "5. Kontak",
    "privacy.s5.descPrefix": "Jika ada pertanyaan tentang kebijakan ini, hubungi melalui form di",
    "privacy.s5.link": "halaman Contact",
    "privacy.s5.suffix": "atau email langsung ke pemilik situs.",
    "privacy.back": "← KEMBALI KE HOME",
  },
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.skill": "Skill",
    "nav.project": "Project",
    "nav.certificate": "Certificates",
    "nav.sourceCode": "Source Code",
    "nav.contact": "Contact",
    "footer.contactTitle": "CONTACT",
    "footer.infoTitle": "INFO",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.madeWith": "Made by R.A.F with love",
    "footer.copyright": "All rights reserved.",
    "sourceModal.title": "OPEN GITHUB REPO?",
    "sourceModal.desc": "This opens this portfolio's GitHub repo in a new tab. You stay on this page.",
    "sourceModal.continue": "CONTINUE",
    "sourceModal.back": "← BACK",
    "notFound.title": "404",
    "notFound.desc":
      "The page you are looking for does not exist. It may have been removed, or you mistyped the URL. Please check the address again, or return to the homepage.",
    "notFound.back": "BACK TO HOME →",
    "privacy.title": "PRIVACY POLICY",
    "privacy.updated": "Last updated: September 15, 2026 — placeholder, replace with your actual policy if needed.",
    "privacy.intro":
      "This portfolio website respects visitor privacy. This page explains what information is collected and how it is used. This is placeholder text — please replace it with a privacy policy that fits your legal needs and the services you use (e.g., Web3Forms for the contact form).",
    "privacy.s1.title": "1. Information Collected",
    "privacy.s1.desc":
      "The contact form on the Contact page sends the name, email, and message you enter to a third-party service (Web3Forms or Formspree) to be forwarded to the site owner's email. No other data is stored on this site's server because the site is hosted as a static site on GitHub Pages.",
    "privacy.s2.title": "2. Use of Information",
    "privacy.s2.desc":
      "Information sent via the form is only used to reply to messages and is not shared with other parties. Anonymous logs (as provided by GitHub Pages) may record page visits for statistics without identifying individuals.",
    "privacy.s3.title": "3. Cookies",
    "privacy.s3.desc":
      "This site does not use tracking cookies. Language preference is stored in the browser's localStorage (portfolio:language) and is not sent to the server.",
    "privacy.s4.title": "4. External Links",
    "privacy.s4.desc":
      "Links to GitHub, LinkedIn, and Instagram will open third-party sites with their own privacy policies. Please review their policies before interacting further.",
    "privacy.s5.title": "5. Contact",
    "privacy.s5.descPrefix": "If you have questions about this policy, please contact via the form on the",
    "privacy.s5.link": "Contact page",
    "privacy.s5.suffix": "or email the site owner directly.",
    "privacy.back": "← BACK TO HOME",
  },
};
