export const contactText = {
  id: {
    kicker: "// let's connect",
    heading: "HIT ME UP",
    subtitle: "Ada project, kerjaan, atau cuma mau ngobrol soal coding? Gas cari aku lewat salah satu ini.",
    email: "Email",
    github: "GitHub",
    linkedin: "LinkedIn",
    instagram: "Instagram",
    formNameLabel: "NAMA",
    formNamePlaceholder: "Nama lengkap",
    formEmailLabel: "EMAIL",
    formEmailPlaceholder: "email@contoh.com",
    formMessageLabel: "PESAN",
    formMessagePlaceholder: "Tulis pesanmu di sini...",
    formSubmit: "KIRIM PESAN →",
    formSending: "MENGIRIM...",
    formSuccess: "Pesan terkirim! Terima kasih sudah menghubungi — akan dibalas secepatnya.",
    formErrorRequired: "Semua field wajib diisi.",
    formErrorNotConfigured: "Form belum dikonfigurasi — ganti WEB3FORMS_ACCESS_KEY di app/contact/page.tsx dengan key dari web3forms.com",
    formErrorGeneric: "Gagal mengirim. Coba lagi.",
    formErrorNetwork: "Gagal terhubung ke server. Cek koneksi.",
  },
  en: {
    kicker: "// let's connect",
    heading: "HIT ME UP",
    subtitle: "Got a project, job, or just want to chat about coding? Reach me through one of these.",
    email: "Email",
    github: "GitHub",
    linkedin: "LinkedIn",
    instagram: "Instagram",
    formNameLabel: "NAME",
    formNamePlaceholder: "Full name",
    formEmailLabel: "EMAIL",
    formEmailPlaceholder: "email@example.com",
    formMessageLabel: "MESSAGE",
    formMessagePlaceholder: "Write your message here...",
    formSubmit: "SEND MESSAGE →",
    formSending: "SENDING...",
    formSuccess: "Message sent! Thanks for reaching out — I'll reply soon.",
    formErrorRequired: "All fields are required.",
    formErrorNotConfigured: "Form not configured — replace WEB3FORMS_ACCESS_KEY in app/contact/page.tsx with your key from web3forms.com",
    formErrorGeneric: "Failed to send. Please try again.",
    formErrorNetwork: "Failed to connect to server. Check your connection.",
  },
};
