export const projectText = {
  id: {
    kicker: "// karya-karya",
    heading: "PROJECT",
    back: "← KEMBALI KE SEMUA PROJECT",
    backShort: "← KEMBALI KE PROJECT",
    roleLabel: "PERAN:",
    techStackLabel: "TECH STACK",
    sourceCode: "SOURCE CODE ↗",
    liveDemo: "LIVE DEMO ↗",
    viewSource: "Lihat source code →",
    viewDemo: "Demo →",
    viewDetail: "LIHAT DETAIL →",
    thumbnailFallback: "THUMBNAIL",
    thumbnailDesc: "PROJECT DI SINI",
    ctaNew: "[ISI SENDIRI: tidak ada CTA tambahan — hapus jika tidak perlu]",
  },
  en: {
    kicker: "// works",
    heading: "PROJECT",
    back: "← BACK TO ALL PROJECTS",
    backShort: "← BACK TO PROJECTS",
    roleLabel: "ROLE:",
    techStackLabel: "TECH STACK",
    sourceCode: "SOURCE CODE ↗",
    liveDemo: "LIVE DEMO ↗",
    viewSource: "View source →",
    viewDemo: "Demo →",
    viewDetail: "VIEW DETAIL →",
    thumbnailFallback: "THUMBNAIL",
    thumbnailDesc: "PROJECT HERE",
    ctaNew: "[FILL IN: no extra CTA — delete if not needed]",
  },
};
